######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 11 15:48:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += effect.h
FORMS += effect.ui
SOURCES += effect.cpp main.cpp
